config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length: {minimum: 4, maximum: 50}
	validates :description, presence: true, length: {minimum: 5, maximum: 100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def show
		@article = Article.find(params[:id])
	end

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		puts "-"*20
		puts params
		puts "-"*20
		@article = Article.new(params.require(:article).permit(:title, :description));
		if @article.save
			flash[:notice] = "Article created successully"
			redirect_to article_path(@article)
		else
			puts "*"*20
			puts @article.errors.full_messages
			puts "*"*20
			render 'new'
		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(params.require(:article).permit(:title, :description))
			flash[:notice] = "Article updated successully"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def destroy
		puts 'came to destroy'
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1> Edit this article </h1>

<% if @article.errors.any? %>
	<h3>Following errors are preventing you from saving the article</h3>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end %>
	</ul>
<% end %>
<%= form_with(model: @article, local: true, data: { turbo: false }) do |f| %>
	<p>
		<%= f.label :title %>
		<br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :description %>
		<br>
		<%= f.text_area :description %>
	</p>

	<%= f.submit %>
<% end %>

<%= link_to 'Return to articles listing', articles_path %> 

app/views/articles/index.html.erb
<h1> This is index page....</h1>

<table>
	<thead>
		<tr>
			<th> Title </th>
			<th> description </th>
			<th> Actions </th>
		</tr>
	</thead>
	<tbody>
		<% @articles.each do |article| %>
			<tr>
				<td>
					<%= article.title %>
				</td>
				<td>
					<%= article.description %>
				</td>

				<td>
					<%= link_to 'Show', article_path(article) %>
					<%= link_to 'Edit', edit_article_path(article) %>
					<%= link_to 'Delete', article_path(article), data: { "turbo-method": :delete } %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<p>
	<%= link_to 'Create new article', new_article_path %> | <%= link_to 'Go back to home page', root_path %>
</p>

app/views/articles/new.html.erb
<h1> Add a new article </h1>

<% if @article.errors.any? %>
	<h3>Following errors are preventing you from saving the article</h3>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
		<% end %>
	</ul>
<% end %>
<%= form_with scope: :article, url: articles_path, local: true do |f| %>
	<p>
		<%= f.label :title %>
		<br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :description %>
		<br>
		<%= f.text_area :description %>
	</p>

	<%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h1>This is show page</h1>

<p>Article:- <%= @article.title %> </p>
<p>Description:- <%= @article.description %> </p>

<%= link_to 'Edit this article', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article), data: { "turbo-method": :delete, confirm: "Are you sure?" } %> |
<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, msg| %>
    <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> About Page </h1>

<%= link_to 'Go back to home page', root_path %>

app/views/pages/home.html.erb
<h1> This is home page </h1>

<%= link_to 'Go to articles listing page', articles_path %> | 
<%= link_to 'Go to about page', about_path %>